name: CI

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "go.mod"
      - "go.sum"
      - "ui/pnpm-lock.yaml"
      - "ui/package.json"
      - "ui/vite.config.ts"
      - "ui/tsconfig*.json"
      - "ui/eslint.config.js"
      - "docs/**"
      - "README.md"
      - "README_zh.md"
      - ".dockerignore"
      - "Dockerfile*"
      - "charts/**"
      - "deploy/**"
      - "scripts/**"
      - "Makefile"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - ".github/workflows/ci.yml"
      - "go.mod"
      - "go.sum"
      - "ui/pnpm-lock.yaml"
      - "ui/package.json"
      - "ui/vite.config.ts"
      - "ui/tsconfig*.json"
      - "ui/eslint.config.js"
      - "docs/**"
      - "README.md"
      - "README_zh.md"
      - ".dockerignore"
      - "Dockerfile*"
      - "charts/**"
      - "deploy/**"
      - "scripts/**"
      - "Makefile"
      - ".github/workflows/**"

env:
  GO_VERSION: "1.26"
  NODE_VERSION: "24"

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v5
        with:
          version: 10.30.2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: |
            ui/pnpm-lock.yaml
            docs/pnpm-lock.yaml

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          check-latest: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --yes ripgrep

      - name: Install deps
        run: make deps
      - name: Build
        run: make build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
      - name: lint
        run: make verify
      - name: Test
        run: make test
      - name: Documentation
        run: make docs-build
